# Use root/mysql as user/password credentials
version: "3.1"
services:
  db:
    image: mysql:5.7.34
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: jwt_demo
      MYSQL_PASSWORD: jwt_demo
      MYSQL_DATABASE: jwt_db
    ports:
      - 3377:3306
    volumes:
      - mysql-data-jwt:/var/lib/mysql

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8077:8080

volumes:
  mysql-data-jwt:
